### ISSUE TITLE
Layout to discuss

### ISSUE THREAD

**Issue by LeticiaMatosGuerra** [santiagorave/projectJS#5]
- [x] colors
- [x]  brand
- [x] layout it self

**Comment by santiagorave** [comment]
Color Palette: https://colorhunt.co/palette/f1f6f9394867212a3e9ba4b5

**Comment by MiguelARey** [comment]
https://www.figma.com/file/TzBJ3S52bRLXQ7bpGTvTUf/Streaming-Platform?t=V9BnR57cC5aOCgsP-0

**Comment by santiagorave** [comment]
Done!
